version: '3.3'
services:
  pilipala-web:
    image: cxyjerry/pilipala-web:v1.0.6
    ports:
      - "80:8888"
      - "443:443"
    volumes:
      - /home/pilipala-web/nginx.conf:/etc/nginx/nginx.conf
      - /home/pilipala-web/cert:/etc/nginx/cert