version: '3.3'
services:
  pilipala-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8888"
    volumes:
      - /home/pilipala-web/nginx.conf:/etc/nginx/nginx.conf
